//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestManagmentMPSApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Number { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public string Text { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual User User { get; set; }
    }
}
